### ISSUE TITLE
"Dict" is used as a variable name

### ISSUE THREAD

**Issue by nyboer** [rec/swirly#23]
In the compile .jso, I found that Dict is used as a name for an object. This ends up ruining any attempt at using the actual [dict] object in other JS. Max throws the error "Dict is not a constructor" when I try to use it in JS. You can see this in the dict helpfile in the js tab.

**Comment by rec** [comment]
Sorry for the delay, I took a day AFK.

To be honest, I haven't touched this in many years.  I could easily do a find and replace on Dict and release a fix, even though I wouldn't be sure if it worked...?

**Comment by rec** [comment]
I renamed Dict to Dicti everywhere: https://github.com/rec/swirly/pull/24

Javascript is case _sensitive_ so I might add that it is thoroughly stupid, whatever piece of software it is that mistakes `Dict` for `dict`. :-D

Lemme know if you have any success with the software!
